language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4

addons:
  apt:
    packages:
      - parallel
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="127.0.0.1"
    - TYPO3_DATABASE_USERNAME="root"
    - TYPO3_DATABASE_PASSWORD=""
    - EXT_SOLR_VERSION="dev-release-11.0.x"

  matrix:
    - TYPO3_VERSION="^9.5.0"
    - TYPO3_VERSION="^10.4.0"

matrix:
  fast_finish: true

before_install:
  - composer self-update
  - composer --version

install:
  - Build/Test/bootstrap.sh

script:
  - Build/Test/cibuild.sh

after_script:
  - Build/Test/cleanup.sh

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/solr/downloads
